# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://jurgen-kluft.github.io"

# Site title
title = "Personal Information"
copyright = "Jurgen"
languageCode = "en-EN"
canonifyurls = true

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap"

# Pagination
paginate = 3
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "Jurgen"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Jurgen"
    email = "jurgen.kluft@gmail.com"

[markup.goldmark.renderer]
unsafe = true

